### ISSUE TITLE
请问从huggingface下载的模型怎么使用

### ISSUE THREAD

**Issue by miludedeng** [Ethan-yt/guwenbert#17]
你好：
       我从huggingface上面下载了guwen-punc的模型，通过readme获得到了tokenizer和model。请问我该怎么才能或得到像在huggingface上面api那样或得到json呢

**Comment by Ethan-yt** [comment]
可以参考huggingface的文档。一般的流程都是将你的输入送进tokenizer，获得token_id，然后送入模型，最后获得输出。
https://huggingface.co/transformers/

**Comment by miludedeng** [comment]
谢谢，使用pipeline就可以了，感谢你提供的模型



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ethan ***@***.***&gt;
发送时间: 2021年11月10日 12:53
收件人: Ethan-yt/guwenbert ***@***.***&gt;
抄送: miludedeng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Ethan-yt/guwenbert] 请问从huggingface下载的模型怎么使用 (Issue #17)





 
可以参考huggingface的文档。一般的流程都是将你的输入送进tokenizer，获得token_id，然后送入模型，最后获得输出。
 https://huggingface.co/transformers/

**Comment by miludedeng** [comment]
输入文本的长度有限制，可以通过什么方式调大一点吗

**Comment by Ethan-yt** [comment]
没有，分两次输入吧。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: miludedeng ***@***.***&gt;
发送时间: 2021年11月11日 17:19
收件人: Ethan-yt/guwenbert ***@***.***&gt;
抄送: Ethan ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Ethan-yt/guwenbert] 请问从huggingface下载的模型怎么使用 (Issue #17)






输入文本的长度有限制，可以通过什么方式调大一点吗

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YKKKKKKK** [comment]
可以给的样例运行代码吗，我怎么无论输入什么case，预测的都是 “时”

**Comment by YKKKKKKK** [comment]
`from transformers import AutoTokenizer, AutoModelForMaskedLM
import torch, os

path_1 = 'guwenbert-base'

os.environ["CUDA_VISIBLE_DEVICES"] = '2'
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

tokenizer = AutoTokenizer.from_pretrained(path_1)
model = AutoModelForMaskedLM.from_pretrained(path_1).to(DEVICE)`

这样加载出来了

**Comment by jiangliqin** [comment]
> 谢谢，使用pipeline就可以了，感谢你提供的模型 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Ethan ***@***.***&gt; 发送时间: 2021年11月10日 12:53 收件人: Ethan-yt/guwenbert ***@***.***&gt; 抄送: miludedeng ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [Ethan-yt/guwenbert] 请问从huggingface下载的模型怎么使用 (Issue #17) 可以参考huggingface的文档。一般的流程都是将你的输入送进tokenizer，获得token_id，然后送入模型，最后获得输出。 https://huggingface.co/transformers/ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我这边使用pipeline报错，请问你是怎么使用的？
